a=('aa' 'bb' 'cc')
echo "no of variables passed: $#"
echo "print all vars : ${a[@]}"
echo "print current working dir : $PWD"
echo "print script name: $o"
echo "print home dir: $HOME"
echo "print current user : $USER"
echo "print hostname: $HOSTNAME"
echo "process id of the shell script: $$"
echo "process id of the last backgroung cmd: $!"
