- name: install nginx and run #task name
  hosts: web
  become: yes # giving elevated privilages
  tasks:
  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
