#Taking variables from other files
- name: vars from files
  hosts: localhost
  vars_files:
  - var.yaml
  tasks:
  - name: printing
    ansible.builtin.debug:
      msg: "hi course is {{course}} {{duration}} {{name}}"
