#variables from prompt
- name: vars prompt
  hosts: localhost
  vars_prompt:
    - name: usrname
      prompt: "enter username"
      private: false
    - name: passwd
      prompt: "enter passwd"
      private: true
  tasks:
    - name: printing
      ansible.builtin.debug:
        msg: "username: {{usrname}}. password is {{passwd}}"




# - name: vars prompt
#   hosts: localhost
#   vars_prompt:
#     - name: usrname
#       prompt: "Enter username"
#       private: false
#     - name: passwd
#       prompt: "Enter password"
#       private: true
#   tasks:
#     - name: Printing username
#       ansible.builtin.debug:
#         msg: "Username: {{ usrname }}"
