- name: vars prompt
  hosts: localhost
  vars_prompt:
    - name: usrname
      prompt: "Enter username"
      private: false
    - name: passwd
      prompt: "Enter password"
      private: true
  tasks:
    - name: Printing username
      ansible.builtin.debug:
        msg: "Username: {{ usrname }}"
