#for loops item is the keyword
- name: loops
  hosts: localhost
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "hello {{item}} "
    loop:
    - linuc
    - shell
    - vishnu
 
 - name: install pacakages
   hosts: web
   become: yes
   tasks:
   - name: install
     ansible.builtin.dnf:
        name: "{{item}}"
        state: latest
      loop:
      - mysql
      - curl
      - postfix
      
    
   